  UILANG="Polski"  
  label="ID (uid/gid)"  
  label_homeDir="Katalog domowy"  
  label_loginShell="Powłoka logowania"  
  label_realName="Prawdziwe imię"  
  label_room="Pokój"  
  label_workPhone="Telefon do pracy"  
  label_phone="Telefon domowy"  
  label_comment="Komentarz"
  
  field_descriptions[1]="Nazwa użytkownika;Login użytkownika;nazwa"
  field_descriptions[2]="Hasło;Zastępnik zaszyfrowanego hasła (zwykle 'x')"
  field_descriptions[3]="UID;Numer identyfikacyjny użytkownika"
  field_descriptions[4]="GID;Numer identyfikacyjny grupy podstawowej"
  field_descriptions[5]="GECOS;Informacje o użytkowniku (pełne imię i nazwisko, dane kontaktowe)"
  field_descriptions[6]="Katalog domowy;Ścieżka do katalogu domowego użytkownika;katalog"
  field_descriptions[7]="Powłoka logowania;Ścieżka do domyślnej powłoki użytkownika;powloka"
  
ERROR="BŁĄD"
ERR_INCORRECT_FIELD="Podano błędną nazwę lub numer pola"
INFO_CORRECT_FIELDS="Proszę użyć poprawnej nazwy pola lub numeru pola!"
AVAILABLE_FIELD_NAMES="Dostępne nazwy pól"
AVAILABLE_FIELD_NUMBERS="Dostępne numery pól"

FIELD="Pole Danych"
