Spanische Variablenwerte:
  UILANG="Spanish"
  label_ID="IDs (uid/gid)"
  label_homeDir="Directorio personal"
  label_loginShell="Shell de inicio de sesión"
  label_realName="Nombre real"
  label_room="Habitación"
  label_workPhone="Teléfono de trabajo"
  label_phone="Teléfono de casa"
  label_comment="Comentario"
