  UILANG="Ελληνικά"  
  label="Ταυτοποίησεις (uid/gid)"  
  label_homeDir="Κατάλογος"  
  label_loginShell="Shell σύνδεσης"  
  label_realName="Πραγματικό Όνομα"  
  label_room="Δωμάτιο"  
  label_workPhone="Τηλέφωνο εργασίας"  
  label_phone="Τηλέφωνο σπιτιού"  
  label_comment="Σχόλιο"
  
  field_descriptions[1]="Όνομα χρήστη;Όνομα σύνδεσης του χρήστη;Όνομα"
  field_descriptions[2]="Κωδικός πρόσβασης;Σύμβολο κράτησης θέσης για κρυπτογραφημένο κωδικό (συνήθως 'x')"
  field_descriptions[3]="UID;Αριθμός αναγνώρισης χρήστη"
  field_descriptions[4]="GID;Αριθμός αναγνώρισης κύριας ομάδας"
  field_descriptions[5]="GECOS;Πληροφορίες χρήστη (πλήρες όνομα, στοιχεία επικοινωνίας)"
  field_descriptions[6]="Αρχικός κατάλογος;Διαδρομή προς τον αρχικό κατάλογο του χρήστη;κατάλογος"
  field_descriptions[7]="Κέλυφος σύνδεσης;Διαδρομή προς το προεπιλεγμένο κέλυφος του χρήστη;κέλυφος"
  
ERROR="ΣΦΑΛΜΑ"
ERR_INCORRECT_FIELD="Λάθος όνομα ή αριθμός πεδίου"
INFO_CORRECT_FIELDS="Παρακαλώ χρησιμοποιήστε ένα έγκυρο όνομα πεδίου ή αριθμό πεδίου!"
AVAILABLE_FIELD_NAMES="Διαθέσιμα ονόματα πεδίων"
AVAILABLE_FIELD_NUMBERS="Διαθέσιμοι αριθμοί πεδίων"

FIELD="Πεδίο Δεδομένων"
